// function to return a list of fallback books
import { Books } from "@/app/types/books";
import { v4 as uuidv4 } from "uuid";

export default function getFallbackBooks(): Books[] {
	const staticBooks: Books[] = [
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 1",
			book_author: "The Mini Library Team",
			book_year: "2025",
			book_finished_reading: true,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 2",
			book_author: "The Mini Library Team",
			book_year: "2024",
			book_finished_reading: false,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 3",
			book_author: "The Mini Library Team",
			book_year: "2023",
			book_finished_reading: true,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 4",
			book_author: "The Mini Library Team",
			book_year: "2022",
			book_finished_reading: false,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 5",
			book_author: "The Mini Library Team",
			book_year: "2021",
			book_finished_reading: true,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 6",
			book_author: "The Mini Library Team",
			book_year: "2020",
			book_finished_reading: false,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 7",
			book_author: "The Mini Library Team",
			book_year: "2019",
			book_finished_reading: true,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 8",
			book_author: "The Mini Library Team",
			book_year: "2018",
			book_finished_reading: false,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 9",
			book_author: "The Mini Library Team",
			book_year: "2017",
			book_finished_reading: true,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 10",
			book_author: "The Mini Library Team",
			book_year: "2016",
			book_finished_reading: false,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 11",
			book_author: "The Mini Library Team",
			book_year: "2015",
			book_finished_reading: true,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 12",
			book_author: "The Mini Library Team",
			book_year: "2014",
			book_finished_reading: false,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 13",
			book_author: "The Mini Library Team",
			book_year: "2013",
			book_finished_reading: true,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 14",
			book_author: "The Mini Library Team",
			book_year: "2012",
			book_finished_reading: false,
		},
		{
			id: uuidv4(),
			created_at: new Date().toISOString(),
			book_title: "Fallback Book 15",
			book_author: "The Mini Library Team",
			book_year: "2011",
			book_finished_reading: true,
		},
	];
	return staticBooks;
}
